name: Deploy to csalinas-dev-sfo3-01
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /var/www/csalinas-dev-site

    steps:
      - name: Stop PM2 process
        run: pm2 stop 0

      - name: Clone repository
        run: |
          git reset --hard
          git pull

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Restart PM2 process
        run: pm2 restart 0
