name: Deploy to csalinas-dev-sfo3-01
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /var/www/csalinas-dev-site

    steps:
      - name: Stop PM2 process
        run: pm2 stop csalinas-dev

      - name: Clone repository
        run: |
          git reset --hard
          git fetch --all
          git checkout ${{ github.sha }}

      - name: Install dependencies
        run: npm i

      - name: Build the application
        run: npm run build

      - name: Restart PM2 process
        run: pm2 restart csalinas-dev
